name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lints:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: DeterminateSystems/nix-installer@fe7c843b6ff5034941ec57f6c7ee2628496a9749
        with:
          # Allow the installed Nix to make authenticated Github requests.
          # If you skip this, you will likely get rate limited.
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - run: nix flake check
      - run: nix run
