name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lints:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          nix-installer-tag: "v0.12.0"
          extra-conf: |
            # Swoop de doop
            # Beep boop
      - run: cat /etc/nix/nix.conf
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check
      - run: nix run
