name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lints:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: DeterminateSystems/nix-installer-action@v3
        with:
          nix-installer-pr: "484"
      - uses: actions/checkout@v3
      - run: nix flake check
      - run: nix run
      - run: nix profile install nixpkgs#hello
      - run: echo $PATH
      - run: ls -lah ~/.nix-profile
      - run: hello
