name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lints:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: DeterminateSystems/nix-installer@main
        with:
          # Allow the installed Nix to make authenticated Github requests.
          # If you skip this, you will likely get rate limited.
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra-conf:
            trusted-users = root runner
      - uses: actions/checkout@v3
      - run: nix flake check
      - run: nix run
      - uses: cachix/cachix-action@v11
        with:
          name: test
          # If you chose signing key for write access
          signingKey: 'bears'
