name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lints:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: DeterminateSystems/nix-installer-action@hoverbear/ds-893-make-installer-action-use-typescript
      - uses: actions/checkout@v3
      - run: nix flake check
      - run: nix run
