name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lints:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: EricCrosson/nix-installer-action@3-add-default-value-for-the-the-github-token-input
      - uses: actions/checkout@v3
      - run: nix flake check
      - run: nix run
